# Generated by Django 4.1.5 on 2023-01-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pprice', models.IntegerField()),
                ('pimage', models.CharField(max_length=40)),
                ('pdscription', models.TextField()),
            ],
        ),
    ]
